import type { Opportunity } from "./types";

/**
 * SAMPLE DATA — clearly labeled demonstration records used until the live
 * ingestion pipeline (SAM.gov, state and local sources) is connected.
 * Values are illustrative and must not be presented as real solicitations.
 */
export const sampleOpportunities: Opportunity[] = [
  {
    id: "ndl-2026-0417",
    productKey: "contracts",
    recordType: "contract",
    title: "Zero Trust Architecture Implementation and Continuous Monitoring",
    agency: "Department of Homeland Security",
    agencyId: "dhs",
    office: "Cybersecurity and Infrastructure Security Agency",
    level: "Federal",
    state: "Virginia",
    stateCode: "VA",
    city: "Arlington",
    postedDate: "2026-08-04",
    deadline: "2026-09-18",
    estimatedValue: 24500000,
    naics: { code: "541512", label: "Computer Systems Design Services" },
    psc: { code: "D310", label: "IT and Telecom — Cyber Security" },
    setAside: "Small Business",
    contractType: "Firm Fixed Price",
    vehicle: "GSA MAS",
    industry: "Cybersecurity",
    clearance: "Secret",
    awardType: "Single Award",
    solicitationNumber: "70RCSA26R00000123",
    aiSummary:
      "A five-year effort to implement zero trust segmentation, identity governance and continuous monitoring across enterprise networks. Scope covers architecture design, phased migration and 24/7 monitoring support. Prior FedRAMP and CDM experience is weighted heavily in the technical evaluation.",
    requirements: [
      "Zero trust reference architecture aligned to CISA ZTMM v2",
      "Identity, credential and access management modernization",
      "24/7 continuous monitoring with defined response SLAs",
      "Migration plan for 40+ legacy applications",
      "Quarterly control assessments and POA&M management",
    ],
    eligibility: [
      "Active SAM.gov registration in good standing",
      "SBA-certified small business under NAICS 541512",
      "Facility clearance at Secret level",
      "CMMC Level 2 or documented remediation plan",
    ],
    timeline: [
      { label: "Solicitation posted", date: "2026-08-04" },
      { label: "Industry day", date: "2026-08-19" },
      { label: "Questions due", date: "2026-08-28" },
      { label: "Proposals due", date: "2026-09-18" },
      { label: "Anticipated award", date: "2026-11-30" },
    ],
    documents: [
      { name: "Solicitation Package", type: "PDF", size: "3.2 MB" },
      { name: "Performance Work Statement", type: "PDF", size: "1.1 MB" },
      { name: "Pricing Workbook", type: "XLSX", size: "240 KB" },
    ],
    intelligence: {
      opportunityScore: 87,
      fitScore: 74,
      competition: "High",
      proposalComplexity: "High",
      risks: [
        "Secret facility clearance required at proposal submission",
        "Aggressive 90-day transition period",
        "Past performance requires three comparable federal ZT engagements",
      ],
      nextSteps: [
        "Register for the August 19 industry day",
        "Confirm facility clearance status with DCSA",
        "Draft teaming plan for 24/7 monitoring coverage",
      ],
    },
  },
  {
    id: "ndl-2026-0392",
    productKey: "contracts",
    recordType: "contract",
    title: "Regional Medical Center Imaging Equipment Replacement",
    agency: "Department of Veterans Affairs",
    agencyId: "va",
    office: "Veterans Health Administration",
    level: "Federal",
    state: "Texas",
    stateCode: "TX",
    city: "San Antonio",
    postedDate: "2026-07-29",
    deadline: "2026-09-04",
    estimatedValue: 8750000,
    naics: { code: "334510", label: "Electromedical Apparatus Manufacturing" },
    psc: { code: "6525", label: "Imaging and Radiologic Equipment" },
    setAside: "SDVOSB",
    contractType: "Firm Fixed Price",
    industry: "Healthcare",
    clearance: "None",
    awardType: "Single Award",
    solicitationNumber: "36C25726R00000441",
    aiSummary:
      "Supply, install and commission MRI and CT systems across three VA facilities, including decommissioning of legacy units, staff training and a five-year service agreement. Delivery scheduling is the primary discriminator alongside uptime guarantees.",
    requirements: [
      "3T MRI and 128-slice CT systems with DICOM integration",
      "Site preparation coordination with facility engineering",
      "Five-year full-service maintenance with 98% uptime",
      "Clinical applications training for 60+ staff",
    ],
    eligibility: [
      "Verified SDVOSB in SBA certification database",
      "OEM authorization letter for proposed equipment",
      "FDA 510(k) clearance for all proposed systems",
    ],
    timeline: [
      { label: "Solicitation posted", date: "2026-07-29" },
      { label: "Site visit", date: "2026-08-12" },
      { label: "Questions due", date: "2026-08-20" },
      { label: "Proposals due", date: "2026-09-04" },
    ],
    documents: [
      { name: "Solicitation", type: "PDF", size: "2.4 MB" },
      { name: "Equipment Specifications", type: "PDF", size: "860 KB" },
    ],
    intelligence: {
      opportunityScore: 79,
      fitScore: 68,
      competition: "Moderate",
      proposalComplexity: "Moderate",
      risks: [
        "OEM authorization must be current at submission",
        "Site readiness dependencies outside contractor control",
      ],
      nextSteps: [
        "Attend the August 12 site visit",
        "Secure OEM authorization letters",
        "Model five-year service cost exposure",
      ],
    },
  },
  {
    id: "ndl-2026-0388",
    productKey: "contracts",
    recordType: "contract",
    title: "Statewide Broadband Infrastructure Design-Build Program",
    agency: "Virginia Department of Transportation",
    agencyId: "vdot",
    level: "State",
    state: "Virginia",
    stateCode: "VA",
    city: "Richmond",
    postedDate: "2026-08-01",
    deadline: "2026-10-15",
    estimatedValue: 62000000,
    naics: { code: "237130", label: "Power and Communication Line Construction" },
    setAside: "Full and Open",
    contractType: "IDIQ",
    industry: "Construction",
    clearance: "None",
    awardType: "Multiple Award",
    solicitationNumber: "VDOT-2026-BB-0092",
    aiSummary:
      "Multi-award IDIQ for design-build fiber deployment along state right-of-way corridors, prioritizing unserved rural districts. Task orders are competed among awardees; bonding capacity and self-perform ratio drive scoring.",
    requirements: [
      "Design-build delivery across six highway districts",
      "Minimum $15M single-project bonding capacity",
      "DBE participation goal of 12%",
      "Traffic control plans meeting VDOT standards",
    ],
    eligibility: [
      "Virginia contractor license Class A",
      "Prequalification with VDOT prior to submission",
      "Three comparable fiber projects in the last five years",
    ],
    timeline: [
      { label: "Solicitation posted", date: "2026-08-01" },
      { label: "Prequalification deadline", date: "2026-09-10" },
      { label: "Proposals due", date: "2026-10-15" },
      { label: "Anticipated awards", date: "2026-12-18" },
    ],
    documents: [
      { name: "RFP Package", type: "PDF", size: "5.6 MB" },
      { name: "Corridor Maps", type: "ZIP", size: "18 MB" },
    ],
    intelligence: {
      opportunityScore: 91,
      fitScore: 61,
      competition: "High",
      proposalComplexity: "High",
      risks: [
        "Prequalification deadline precedes proposal deadline by five weeks",
        "DBE participation goal may require new subcontractor relationships",
      ],
      nextSteps: [
        "Start VDOT prequalification immediately",
        "Confirm surety capacity for concurrent task orders",
        "Identify DBE partners in rural districts",
      ],
    },
  },
  {
    id: "ndl-2026-0361",
    productKey: "contracts",
    recordType: "contract",
    title: "Cloud Migration and Managed Platform Services",
    agency: "General Services Administration",
    agencyId: "gsa",
    office: "Federal Acquisition Service",
    level: "Federal",
    state: "District of Columbia",
    stateCode: "DC",
    city: "Washington",
    postedDate: "2026-08-08",
    deadline: "2026-09-29",
    estimatedValue: 15200000,
    naics: { code: "518210", label: "Computing Infrastructure Providers" },
    psc: { code: "D399", label: "IT and Telecom — Other" },
    setAside: "8(a)",
    contractType: "Time and Materials",
    vehicle: "Alliant 2",
    industry: "Information Technology",
    clearance: "Public Trust",
    awardType: "Single Award",
    solicitationNumber: "47QFCA26R0031",
    aiSummary:
      "Migration of 22 mission applications to a FedRAMP High environment with ongoing managed platform operations, DevSecOps pipeline support and FinOps reporting. Evaluation is best value tradeoff with heavy weighting on migration methodology.",
    requirements: [
      "Application discovery and migration wave planning",
      "FedRAMP High boundary operations",
      "CI/CD pipeline modernization and IaC baselines",
      "Monthly FinOps and utilization reporting",
    ],
    eligibility: [
      "Active 8(a) certification through award date",
      "Alliant 2 contract holder",
      "Public Trust eligible personnel",
    ],
    timeline: [
      { label: "Solicitation posted", date: "2026-08-08" },
      { label: "Questions due", date: "2026-09-02" },
      { label: "Proposals due", date: "2026-09-29" },
    ],
    documents: [
      { name: "Statement of Work", type: "PDF", size: "1.8 MB" },
      { name: "Application Inventory", type: "XLSX", size: "410 KB" },
    ],
    intelligence: {
      opportunityScore: 83,
      fitScore: 88,
      competition: "Moderate",
      proposalComplexity: "Moderate",
      risks: ["8(a) certification must remain active through award"],
      nextSteps: [
        "Validate Alliant 2 on-ramp status",
        "Assemble migration case studies at FedRAMP High",
      ],
    },
  },
  {
    id: "ndl-2026-0344",
    productKey: "contracts",
    recordType: "contract",
    title: "Municipal Water Treatment Plant Rehabilitation",
    agency: "City of Phoenix Water Services",
    agencyId: "phoenix-water",
    level: "Local",
    state: "Arizona",
    stateCode: "AZ",
    city: "Phoenix",
    postedDate: "2026-07-22",
    deadline: "2026-08-28",
    estimatedValue: 4300000,
    naics: { code: "237110", label: "Water and Sewer Line Construction" },
    setAside: "Full and Open",
    contractType: "Firm Fixed Price",
    industry: "Construction",
    clearance: "None",
    awardType: "Single Award",
    solicitationNumber: "PHX-WS-26-114",
    aiSummary:
      "Rehabilitation of clarifier basins, pump station controls and chemical feed systems at a municipal treatment facility. Work must be phased to maintain continuous plant operations, which constrains sequencing and shutdown windows.",
    requirements: [
      "Phased construction with no service interruption",
      "SCADA controls upgrade and commissioning",
      "Arizona-licensed general contractor",
    ],
    eligibility: ["City of Phoenix vendor registration", "Bid bond of 10% of total bid"],
    timeline: [
      { label: "Bid posted", date: "2026-07-22" },
      { label: "Pre-bid conference", date: "2026-08-05" },
      { label: "Bids due", date: "2026-08-28" },
    ],
    documents: [
      { name: "Bid Documents", type: "PDF", size: "9.1 MB" },
      { name: "Plan Set", type: "PDF", size: "42 MB" },
    ],
    intelligence: {
      opportunityScore: 72,
      fitScore: 55,
      competition: "Moderate",
      proposalComplexity: "Low",
      risks: ["Short bid window", "Shutdown windows limited to overnight hours"],
      nextSteps: ["Confirm bid bond capacity", "Review plan set for phasing constraints"],
    },
  },
  {
    id: "ndl-2026-0330",
    productKey: "contracts",
    recordType: "contract",
    title: "Tactical Communications Equipment Sustainment",
    agency: "Department of Defense",
    agencyId: "dod",
    office: "Defense Logistics Agency",
    level: "Federal",
    state: "Pennsylvania",
    stateCode: "PA",
    city: "Philadelphia",
    postedDate: "2026-08-10",
    deadline: "2026-11-06",
    estimatedValue: 38900000,
    naics: { code: "334220", label: "Radio and Television Broadcasting Equipment" },
    psc: { code: "5820", label: "Radio and Television Communication Equipment" },
    setAside: "Full and Open",
    contractType: "IDIQ",
    vehicle: "DLA Prime Vendor",
    industry: "Defense",
    clearance: "Secret",
    awardType: "Multiple Award",
    solicitationNumber: "SPE7M126R0088",
    aiSummary:
      "Long-term sustainment of tactical radio and networking equipment including depot-level repair, spares management and obsolescence engineering. Supply chain traceability and counterfeit prevention controls are mandatory pass/fail criteria.",
    requirements: [
      "Depot repair capability with certified test benches",
      "Counterfeit parts prevention program per SAE AS5553",
      "Spares forecasting and stocking commitments",
    ],
    eligibility: [
      "Facility clearance at Secret level",
      "ITAR registration",
      "AS9100 or equivalent quality certification",
    ],
    timeline: [
      { label: "Solicitation posted", date: "2026-08-10" },
      { label: "Questions due", date: "2026-09-15" },
      { label: "Proposals due", date: "2026-11-06" },
    ],
    documents: [
      { name: "Solicitation", type: "PDF", size: "4.4 MB" },
      { name: "Quality Requirements", type: "PDF", size: "620 KB" },
    ],
    intelligence: {
      opportunityScore: 88,
      fitScore: 47,
      competition: "High",
      proposalComplexity: "High",
      risks: [
        "ITAR and AS9100 are pass/fail gates",
        "Obsolescence engineering requires OEM data rights",
      ],
      nextSteps: ["Confirm ITAR registration currency", "Assess depot test bench coverage"],
    },
  },
];

export const trendingCategories = [
  "Cybersecurity",
  "Cloud Services",
  "Healthcare Equipment",
  "Construction",
  "Professional Services",
  "Logistics",
];

export const popularAgencies = [
  { name: "Department of Defense", id: "dod" },
  { name: "Department of Veterans Affairs", id: "va" },
  { name: "General Services Administration", id: "gsa" },
  { name: "Department of Homeland Security", id: "dhs" },
  { name: "Department of Health and Human Services", id: "hhs" },
];

export const searchExamples = [
  "Cybersecurity contracts",
  "Virginia IT",
  "Healthcare equipment",
  "Construction",
  "Cloud services",
];
